// Generated by `pnpm icons` from the icon slugs in src/content/homelab.ts — do not edit.
import type { StaticImageData } from 'next/image';
import icon_ansible from './ansible.svg';
import icon_apple from './apple.svg';
import icon_authentik from './authentik.svg';
import icon_calibre from './calibre.svg';
import icon_cilium from './cilium.svg';
import icon_cloudflare from './cloudflare.svg';
import icon_codex from './codex.svg';
import icon_debianLinux from './debian-linux.svg';
import icon_emby from './emby.svg';
import icon_github from './github.svg';
import icon_grafana from './grafana.svg';
import icon_homeAssistant from './home-assistant.svg';
import icon_homepage from './homepage.png';
import icon_kubernetes from './kubernetes.svg';
import icon_loki from './loki.svg';
import icon_mysql from './mysql.svg';
import icon_n8n from './n8n.svg';
import icon_navidrome from './navidrome.svg';
import icon_ombi from './ombi.svg';
import icon_postgresql from './postgresql.svg';
import icon_prometheus from './prometheus.svg';
import icon_protonVpn from './proton-vpn.svg';
import icon_proxmox from './proxmox.svg';
import icon_radarr from './radarr.svg';
import icon_sonarr from './sonarr.svg';
import icon_standardNotes from './standard-notes.svg';
import icon_synapse from './synapse.svg';
import icon_terraform from './terraform.svg';
import icon_tor from './tor.png';
import icon_traefik from './traefik.svg';
import icon_trmnl from './trmnl.svg';
import icon_truenasScale from './truenas-scale.svg';
import icon_unifi from './unifi.svg';
import icon_wireguard from './wireguard.svg';

export const icons = {
	ansible: icon_ansible,
	apple: icon_apple,
	authentik: icon_authentik,
	calibre: icon_calibre,
	cilium: icon_cilium,
	cloudflare: icon_cloudflare,
	codex: icon_codex,
	'debian-linux': icon_debianLinux,
	emby: icon_emby,
	github: icon_github,
	grafana: icon_grafana,
	'home-assistant': icon_homeAssistant,
	homepage: icon_homepage,
	kubernetes: icon_kubernetes,
	loki: icon_loki,
	mysql: icon_mysql,
	n8n: icon_n8n,
	navidrome: icon_navidrome,
	ombi: icon_ombi,
	postgresql: icon_postgresql,
	prometheus: icon_prometheus,
	'proton-vpn': icon_protonVpn,
	proxmox: icon_proxmox,
	radarr: icon_radarr,
	sonarr: icon_sonarr,
	'standard-notes': icon_standardNotes,
	synapse: icon_synapse,
	terraform: icon_terraform,
	tor: icon_tor,
	traefik: icon_traefik,
	trmnl: icon_trmnl,
	'truenas-scale': icon_truenasScale,
	unifi: icon_unifi,
	wireguard: icon_wireguard
} satisfies Record<string, StaticImageData>;

export type IconSlug = keyof typeof icons;
