/**
 * Vendors the dashboardicons.com icons referenced by `services` in
 * src/content/homelab.ts into src/images/homelab/, and regenerates the index
 * module that exports them as static imports (so next/image gets intrinsic
 * dimensions and the browser never makes a third-party request).
 *
 *   pnpm icons            fetch anything missing, prune anything unreferenced
 *   pnpm icons --force    re-download everything
 *
 * Runs on plain Node (type stripping) — no build step, so keep it free of
 * path aliases and anything non-erasable.
 */
import { mkdir, readdir, unlink, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { services } from '../src/content/homelab.ts';

const CDN = 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons';
// SVG preferred; a few icons only ship as PNG
const FORMATS = ['svg', 'png'] as const;

const outDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'images', 'homelab');
const force = process.argv.includes('--force');

const slugs = [...new Set(services.map((s) => s.icon as string))].sort();

for (const slug of slugs) {
	if (!/^[a-z0-9-]+$/.test(slug)) {
		throw new Error(`"${slug}" is not a dashboardicons slug (lowercase, digits and dashes only)`);
	}
}

await mkdir(outDir, { recursive: true });
const existing = new Set(await readdir(outDir));

const fetched: { slug: string; file: string }[] = [];

for (const slug of slugs) {
	const present = FORMATS.map((ext) => `${slug}.${ext}`).find((f) => existing.has(f));
	if (present && !force) {
		fetched.push({ slug, file: present });
		continue;
	}

	let saved: string | undefined;
	for (const ext of FORMATS) {
		const res = await fetch(`${CDN}/${ext}/${slug}.${ext}`);
		if (!res.ok) continue;
		const file = `${slug}.${ext}`;
		await writeFile(join(outDir, file), Buffer.from(await res.arrayBuffer()));
		saved = file;
		break;
	}

	if (!saved) {
		throw new Error(`no icon found for "${slug}" — check the slug at https://dashboardicons.com`);
	}
	console.log(`fetched ${saved}`);
	fetched.push({ slug, file: saved });
}

// prune icons nothing references any more
const keep = new Set(fetched.map((f) => f.file));
for (const file of existing) {
	if (file === 'index.ts' || keep.has(file)) continue;
	await unlink(join(outDir, file));
	console.log(`removed ${file}`);
}

const identifier = (slug: string) =>
	`icon_${slug.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase())}`;
const key = (slug: string) => (slug.includes('-') ? `'${slug}'` : slug);

const index = [
	'// Generated by `pnpm icons` from the icon slugs in src/content/homelab.ts — do not edit.',
	"import type { StaticImageData } from 'next/image';",
	...fetched.map(({ slug, file }) => `import ${identifier(slug)} from './${file}';`),
	'',
	'export const icons = {',
	fetched.map(({ slug }) => `\t${key(slug)}: ${identifier(slug)}`).join(',\n'),
	'} satisfies Record<string, StaticImageData>;',
	'',
	'export type IconSlug = keyof typeof icons;',
	''
].join('\n');

await writeFile(join(outDir, 'index.ts'), index);
console.log(`wrote index.ts with ${fetched.length} icon${fetched.length === 1 ? '' : 's'}`);
