name: Build resume

on:
  workflow_call:
  push:
    branches: ['main']

jobs:
  build-latex-document:
    runs-on: ubuntu-latest
    container: ghcr.io/diegog/latex:latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Copy files to root
        run: cp resume/* .
      
      - name: Build latex document
        run: pdflatex $(pwd)/resume.tex

      - name: Move pdf to static folder
        run: mv resume.pdf static/resume.pdf
      
      - name: Commit rendered pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_TO_COMMIT: static/resume.pdf
          DESTINATION_BRANCH: main 
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          export MESSAGE="Build $FILE_TO_COMMIT from latex"
          export SHA=$( git rev-parse $DESTINATION_BRANCH:$FILE_TO_COMMIT )
          export CONTENT=$( base64 -i $FILE_TO_COMMIT )
          gh api --method PUT /repos/:owner/:repo/contents/$FILE_TO_COMMIT \
            --field message="$MESSAGE" \
            --field content="$CONTENT" \
            --field encoding="base64" \
            --field branch="$DESTINATION_BRANCH" \
            --field sha="$SHA"