
name: Continuous Deployment

on:
  push:
    branches: [ main ]
  pull_request:
   branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Use Node.js 18.12.1
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18.12.1
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: Upload to S3
        run: |
          aws s3 sync ./build s3://"$S3_BUCKET"
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      